include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [lib/logic/utils/**.config.dart, /**.freezed.dart, /**.g.dart]
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    omit_local_variable_types: false
